# 1. 상품코드 별 매출액(판매가 * 판매량) 합계
# 2. 정렬

SELECT p.PRODUCT_CODE, (p.PRICE * o.SALES_TOTAL_AMOUNT) AS SALES
FROM PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;