# 1. 자동차 종류 세단, SUV
# 2. 2022년 11월 1일 ~ 2022년 11월 30일까지 대여가능
# 3. 30일간의 금액이 50만~200만 사이인 자동차
# 4. 자동차 ID, 자동차 종류, 대여금액(FEE)

SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * (1 - REPLACE(p.DISCOUNT_RATE, '%', '')/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE p.DURATION_TYPE = '30일 이상'
AND c.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS(
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    WHERE c.CAR_ID = h.CAR_ID
    AND h.START_DATE <= '2022-11-30'
    AND h.END_DATE >= '2022-11-01'
)
HAVING FEE >= 500000
AND FEE <= 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
