# 1. 보호소에 들어올 때는 중성화 X
# 2. 보호소를 나갈 때는 중성화 O
# 3. 동물 ID, 생물 종, 이름

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS
WHERE ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%'
    OR SEX_UPON_OUTCOME LIKE 'Neutered%'
)
AND SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY ANIMAL_ID ASC;