# 1. 2021년 가입한 전체 회원들 중
# 2. 상품을 구매한 회원 수, 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)>소수점 두번째자리에서 반올림
# 3. 년, 월별로
# 4. 정렬

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN(
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC