# 1. 생산일자 2022년 5월
# 2. 식품ID, 식품 이름, 총매출

SELECT p.PRODUCT_ID, PRODUCT_NAME, p.PRICE * TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
    GROUP BY PRODUCT_ID
) AS o
ON p.PRODUCT_ID = o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;
