# 1. 7월 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량
# 2. 큰 순서대로 상위 3개의 맛

SELECT f.FLAVOR
FROM FIRST_HALF f
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS j ON f.FLAVOR = j.FLAVOR
GROUP BY f.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC
LIMIT 3;