# 1. 7월 아이스크림 총 주문량 + 상반기의 아이스크림 총 주문량
# 2. 큰 순서대로 상위 3개의 맛

SELECT T.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    
    UNION ALL
    
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) AS T
GROUP BY T.FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3;